spring:
  application:
    name: server-mtls
server:
  port: 8432
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:identity.jks
    key-store-password: secret
    key-alias: client
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:truststore.jks
    trust-store-password: secret
    trust-store-type: JKS
